language: rust
rust: [nightly]
cache: cargo
env:
  matrix:
    - RELEASE_FLAG="" NODE_VERSION="10.17"
    - RELEASE_FLAG="--release"

install:
  - "export RUSTFLAGS=$(cargo --version | grep nightly >/dev/null && echo \"-Z external-macro-backtrace\")"
  - "rustup component add rustfmt --toolchain $(rustup show active-toolchain | cut -d\" \" -f1)"
  - "(cd client && npm install)"
  - cargo install just
  - just materialize

script:
  - just build
  - just test
