[package]
name = "webcord"
version = "0.0.0"
authors = ["SOFe <sofe2038@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/SOF3/webcord"
homepage = "https://github.com/SOF3/webcord"
readme = "README.md"
description = "Mirrors Discord chat logs on webpages in a searchable fashion"

[dependencies]
actix-rt = "1.0.0-alpha.3" # selected by actix-web
actix-web = "2.0.0-alpha.5"
config = "0.10.1"
derive_more = "0.99.2"
dirmod = "0.2.0-alpha.1"
dotenv = "0.15.0"
futures = "0.3.1"
getset = "0.0.9"
handlebars = "2.0.2"
lazy_static = "1.4.0"
log = "0.4.8"
pretty_env_logger = "0.3.1"
rand = "0.7.2"
serde = {version = "1.0.103", features = ["std", "derive"]}
serde_json = "1.0.44"
serenity = "0.7.4"
typemap = "0.3.3"
