table! {
    /// Representation of the `channel_hours` table.
    ///
    /// (Automatically generated by Diesel.)
    channel_hours (channel_id, date, hour) {
        /// The `channel_id` column of the `channel_hours` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        channel_id -> Int8,
        /// The `date` column of the `channel_hours` table.
        ///
        /// Its SQL type is `Date`.
        ///
        /// (Automatically generated by Diesel.)
        date -> Date,
        /// The `hour` column of the `channel_hours` table.
        ///
        /// Its SQL type is `Int4`.
        ///
        /// (Automatically generated by Diesel.)
        hour -> Int4,
        /// The `message` column of the `channel_hours` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        message -> Int8,
    }
}

table! {
    /// Representation of the `channels` table.
    ///
    /// (Automatically generated by Diesel.)
    channels (id) {
        /// The `id` column of the `channels` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `guild_id` column of the `channels` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        guild_id -> Int8,
        /// The `cache_name` column of the `channels` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        cache_name -> Varchar,
        /// The `cache_desc` column of the `channels` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        cache_desc -> Text,
    }
}

table! {
    /// Representation of the `guilds` table.
    ///
    /// (Automatically generated by Diesel.)
    guilds (id) {
        /// The `id` column of the `guilds` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `cache_name` column of the `guilds` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        cache_name -> Varchar,
        /// The `online` column of the `guilds` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        online -> Bool,
        /// The `listed` column of the `guilds` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        listed -> Bool,
    }
}

table! {
    /// Representation of the `known_invites` table.
    ///
    /// (Automatically generated by Diesel.)
    known_invites (code) {
        /// The `code` column of the `known_invites` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        code -> Varchar,
        /// The `guild_id` column of the `known_invites` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        guild_id -> Int8,
    }
}

joinable!(channel_hours -> channels (channel_id));
joinable!(channels -> guilds (guild_id));
joinable!(known_invites -> guilds (guild_id));

allow_tables_to_appear_in_same_query!(channel_hours, channels, guilds, known_invites,);
