table! {
    /// Representation of the `channel` table.
    ///
    /// (Automatically generated by Diesel.)
    channel (id) {
        /// The `id` column of the `channel` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `guild` column of the `channel` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        guild -> Nullable<Int8>,
        /// The `cache_name` column of the `channel` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        cache_name -> Nullable<Varchar>,
        /// The `cache_desc` column of the `channel` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        cache_desc -> Nullable<Text>,
    }
}

table! {
    /// Representation of the `channel_day` table.
    ///
    /// (Automatically generated by Diesel.)
    channel_day (channel, date) {
        /// The `channel` column of the `channel_day` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        channel -> Int8,
        /// The `date` column of the `channel_day` table.
        ///
        /// Its SQL type is `Date`.
        ///
        /// (Automatically generated by Diesel.)
        date -> Date,
        /// The `message` column of the `channel_day` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        message -> Nullable<Int8>,
    }
}

table! {
    /// Representation of the `guild` table.
    ///
    /// (Automatically generated by Diesel.)
    guild (id) {
        /// The `id` column of the `guild` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `cache_name` column of the `guild` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        cache_name -> Nullable<Varchar>,
        /// The `listed` column of the `guild` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        listed -> Nullable<Bool>,
    }
}

table! {
    /// Representation of the `known_invite` table.
    ///
    /// (Automatically generated by Diesel.)
    known_invite (code) {
        /// The `code` column of the `known_invite` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        code -> Varchar,
        /// The `guild` column of the `known_invite` table.
        ///
        /// Its SQL type is `Nullable<Int8>`.
        ///
        /// (Automatically generated by Diesel.)
        guild -> Nullable<Int8>,
    }
}

joinable!(channel -> guild (guild));
joinable!(channel_day -> channel (channel));
joinable!(known_invite -> guild (guild));

allow_tables_to_appear_in_same_query!(
    channel,
    channel_day,
    guild,
    known_invite,
);
